# Site
name: Ben Greenberg
description: Making developers happy.
meta_description: Ben Greenberg is a developer advocate.
favicon: /assets/images/favicon.ico
paginate: 6
# baseurl: https://www.bengreenberg.dev
email: 'ben.greenberg@vonage.com'
google_analytics: UA-102303776-1
disqus:
sharethis:

# Authors
authors:
  ben:
    name: Ben Greenberg
    display_name: Ben Greenberg
    image: /assets/images/ben.jpg
    email: ben.greenberg@vonage.com
    web: https://www.bengreenberg.dev
    twitter: https://twitter.com/rabbigreenberg
    description: Hey, I'm Ben.

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: rabbigreenberg
  card: summary

facebook:
  app_id:
  publisher: www.bengreenberg.dev
  admins:

social:
name: Ben Greenberg
links:
    - https://twitter.com/rabbigreenberg
    - https://www.linkedin.com/in/rabbigreenberg/
    - https://github.com/bencgreenberg

collections:
  - talks
