name: Convert DEV Posts to Jekyll Markdown
on:
 workflow_dispatch:
 schedule:
     # At midnight twice a week on Monday and Thursday
    - cron:  '0 0 * * 1,4'
jobs:
  dev-to-jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: dev-to-jekyll
      uses: bencgreenberg/dev-posts-to-jekyll-markdown-action@fix-bugs
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_API_KEY: "${{ secrets.DEV_API_KEY }}"
